package data

import (
	"fmt"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestGetFirstLineEmptyContent(t *testing.T) {
	require.Nil(t, getFirstLine(nil))
}

func TestForEachLine(t *testing.T) {
	const sample = "foo\nbar\nboomboom\nbleepbloop\n"
	var lines = strings.Split(sample, "\n")

	var result []string
	forEachLine([]byte(sample), func(l []byte) {
		result = append(result, string(l))
	})

	require.Equal(t, lines[:len(lines)-1], result)
}

func TestGetLines(t *testing.T) {
	const sample = "foo\nbar\nboomboom\nbleepbloop\n"

	testCases := []struct {
		lines    int
		expected []string
	}{
		{1, []string{"foo"}},
		{2, []string{"foo", "bar"}},
		{10, []string{"foo", "bar", "boomboom", "bleepbloop"}},
		{-1, []string{"bleepbloop"}},
		{-2, []string{"bleepbloop", "boomboom"}},
		{-10, []string{"bleepbloop", "boomboom", "bar", "foo"}},
	}

	for _, tt := range testCases {
		t.Run(fmt.Sprint(tt.lines), func(t *testing.T) {
			lines := getLines([]byte(sample), tt.lines)

			var result = make([]string, len(lines))
			for i, l := range lines {
				result[i] = string(l)
			}

			require.Equal(t, tt.expected, result)
		})
	}
}

func TestCompiledCoffeeScript(t *testing.T) {
	for _, content := range []string{
		"// Generated by CoffeeScript 2.7.0\nconsole.log('hello');\n",
		"(function() {\n  var __bind = function(fn, me) {};\n}).call(this);\n",
	} {
		require.True(t, isCompiledCoffeeScript("sample.js", ".js", []byte(content)))
	}
	require.False(t, isCompiledCoffeeScript("sample.js", ".js", []byte("(function() {\n  var ordinary = 1;\n}).call(this);\n")))
}

func TestReverseLinesBoundaries(t *testing.T) {
	for _, text := range []string{"x", "x\n", "a\nx", "a\n\n", "\n", ""} {
		forward := getLines([]byte(text), 10)
		reverse := getLines([]byte(text), -10)
		require.Equal(t, len(forward), len(reverse), text)
		for i := range forward {
			require.Equal(t, forward[i], reverse[len(reverse)-1-i], text)
		}
	}
}

func TestGeneratedFooterBoundaries(t *testing.T) {
	for _, ending := range []string{"", "\n"} {
		require.True(t, isVCRCassette("cassette.yml", ".yml", []byte("---\nhttp_interactions: []\nrecorded_with: VCR 6.0.0"+ending)))
	}
	require.False(t, isVCRCassette("cassette.yml", ".yml", []byte("recorded_with: VCR 6.0.0\nx")))
	require.False(t, hasSourceMapReference("code.js", ".js", []byte("//# sourceMappingURL=code.js.map\nx\ny")))
}
